apiVersion: v1
kind: Service
metadata:
  name: velocity-proxy
  namespace: astera
spec:
  type: NodePort
  selector:
    app: velocity-proxy
  ports:
    - name: velocity
      port: 25577
      targetPort: 25577
      nodePort: 33411
      protocol: TCP
