package com.astarworks.astera.domain.model.economy

/**
 * Astera in-game currencies.
 *
 * - [STAR]: match-bound; generated by Star Generators, used for skill activation, lost on death
 * - [GOLD]: account-bound; earned from match completion, dailies, votes
 * - [GEM]: account-bound; premium / paid currency for cosmetics
 *
 * Convertibility rules are owned by Phase 4 (UGC marketplace + economy).
 */
public enum class Currency {
    STAR,
    GOLD,
    GEM,
}
