apiVersion: v1
kind: Service
metadata:
  name: astera-lobby
  namespace: astera
spec:
  type: ClusterIP
  selector:
    app: astera-lobby
  ports:
    - name: minecraft
      port: 31001
      targetPort: 31001
      protocol: TCP
    - name: rcon
      port: 25575
      targetPort: 25575
      protocol: TCP
